In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
A = np.random.randn(10)

In [6]:
A

array([ 1.39873573,  0.69663457,  1.66301739,  1.28032815,  1.52029204,
       -0.31957628,  0.16108603,  1.27074364, -1.25814631,  1.30701136])

In [7]:
B = np.random.randn(10)

In [8]:
B

array([ 0.94459086, -0.15564062,  3.43613515,  0.00475844, -0.96722001,
        0.02264175, -1.97601639, -0.73725623, -1.62617729,  0.1288549 ])

In [9]:
np.add(A,B)

array([ 2.34332658,  0.54099395,  5.09915254,  1.28508659,  0.55307203,
       -0.29693453, -1.81493036,  0.53348741, -2.8843236 ,  1.43586626])

In [10]:
np.maximum(A,B)

array([ 1.39873573,  0.69663457,  3.43613515,  1.28032815,  1.52029204,
        0.02264175,  0.16108603,  1.27074364, -1.25814631,  1.30701136])

In [11]:
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"
import webbrowser
webbrowser.open(website)

True