In [1]:
import numpy as np

In [2]:
arr = np.arange(5)

In [3]:
np.save('my_array', arr)

In [4]:
arr = np.arange(10)

In [5]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.load('my_array.npy')

array([0, 1, 2, 3, 4])

In [8]:
np.savez('two_arrays.npz', arr_1 = arr, arr_2 = arr)

In [9]:
archive_array = np.load('two_arrays.npz')

In [10]:
archive_array

In [11]:
archive_array['arr_1']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
archive_array['arr_2']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
rm my_array.npy

In [15]:
rm two_arrays.npz

In [16]:
arr = np.array([[1,2,3],[4,5,6]])

In [17]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
arr = np.savetxt('text_array', arr, delimiter=',')

In [21]:
arr = np.loadtxt('text_array', delimiter=',')

In [22]:
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [23]:
np.savez('two_arrays', arr_1 = arr, arr_2 = arr)

In [24]:
rm two_arrays.npz