In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
ser1 = Series(np.arange(3),index=list('TUV'))
ser2 = Series(np.arange(3,5),index=list('XY'))

In [7]:
ser1

T    0
U    1
V    2
dtype: int64

In [8]:
ser2

X    3
Y    4
dtype: int64

In [9]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [10]:
pd.concat([ser1,ser2],axis=1)

0   1
T   0 NaN
U   1 NaN
V   2 NaN
X NaN   3
Y NaN   4

In [11]:
pd.concat([ser1,ser2], keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [12]:
dframe1 = DataFrame(np.random.randn(4,3), columns=list('XYZ'))
dframe2 = DataFrame(np.random.randn(3,3), columns=list('YQX'))

In [13]:
dframe1

X         Y         Z
0 -0.622968  0.771511 -1.107102
1  1.117205  0.482081 -0.894353
2 -0.241890  0.195742 -1.816347
3  1.017408  1.500456 -0.480226

In [14]:
dframe2

Y         Q         X
0  1.805086  1.004758 -0.178238
1 -0.699041  1.862214  0.209170
2 -1.313265  0.732810  1.828763

In [15]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN -0.622968  0.771511 -1.107102
1       NaN  1.117205  0.482081 -0.894353
2       NaN -0.241890  0.195742 -1.816347
3       NaN  1.017408  1.500456 -0.480226
0  1.004758 -0.178238  1.805086       NaN
1  1.862214  0.209170 -0.699041       NaN
2  0.732810  1.828763 -1.313265       NaN

In [16]:
pd.concat([dframe1,dframe2], ignore_index=True)

Q         X         Y         Z
0       NaN -0.622968  0.771511 -1.107102
1       NaN  1.117205  0.482081 -0.894353
2       NaN -0.241890  0.195742 -1.816347
3       NaN  1.017408  1.500456 -0.480226
4  1.004758 -0.178238  1.805086       NaN
5  1.862214  0.209170 -0.699041       NaN
6  0.732810  1.828763 -1.313265       NaN